nodeLinker: node-modules
enableGlobalCache: false
nmMode: hardlinks-local

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-4.7.0.cjs
