[build]
  command = "yarn build"
  publish = ".next"

[[plugins]]
  package = "@netlify/next-runtime"

[build.environment]
  NODE_VERSION = "21.0.0"
  NEXT_PUBLIC_API_BASE_URL = "https://puca-api.vercel.app"
  NETLIFY_USE_YARN = "true"

[[redirects]]
  from = "/api/*"
  to   = "https://puca-api.vercel.app/api/:splat"
  status = 200
