[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"
  LIGHTNINGCSS_BINARY_PATH = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "lightningcss"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://res.cloudinary.com https://cloudinary.com blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' https://puca-api.vercel.app https://res.cloudinary.com;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Robots-Tag = "noindex"

[[redirects]]
  from = "/api/*"
  to = "https://puca-api.vercel.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/image*"
  to = "https://res.cloudinary.com/:splat"
  status = 301
  force = false
  conditions = {Query = {url = "https://res.cloudinary.com/*"}}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[edge_functions]]
  function = "image-optimizer"
  path = "/_next/image/*"

# Configurações de performance
[dev]
  framework = "next"
  targetPort = 3000
  publish = ".next"

# Configurações de imagem
[images]
  remote_images = ["https://res.cloudinary.com/**", "https://cloudinary.com/**"]
