import type { Metadata } from "next";
import { CartProvider } from "@/contexts/CartContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { Inter, Jura } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const jura = Jura({
  subsets: ["latin"],
  variable: "--font-jura",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Puca Coast",
  description: "Generated by create next app",
  icons: [
    {
      url: "/favicon.ico",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jura.variable}`}>
        <AuthProvider>
          <CartProvider>
            {children}
            <ToastContainer position="top-right" autoClose={3000} hideProgressBar />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
