import type { Metadata } from "next";
import { CartProvider } from "@/contexts/CartContext";
import { AuthProvider } from "@/contexts/AuthContext";
import QueryProvider from "@/lib/providers/QueryProvider";
import { AccessibilityProvider } from "@/lib/providers/AccessibilityProvider";
import { ErrorBoundary } from "@/components/ui/ErrorBoundary";
import ClientWrapper from "@/components/providers/ClientWrapper";
import { Inter, Jura } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const jura = Jura({
  subsets: ["latin"],
  variable: "--font-jura",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Puca Coast",
  description: "Generated by create next app",
  icons: [
    {
      url: "/favicon.ico",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jura.variable} flex flex-col min-h-screen`}>
        <ErrorBoundary level="critical">
          <QueryProvider>
            <AccessibilityProvider>
              <ErrorBoundary level="page">
                <AuthProvider>
                  <CartProvider>
                    <ClientWrapper>
                      {children}
                      <ToastContainer position="top-right" autoClose={3000} hideProgressBar />
                    </ClientWrapper>
                  </CartProvider>
                </AuthProvider>
              </ErrorBoundary>
            </AccessibilityProvider>
          </QueryProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
