backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "lookbook"
    label: "Lookbook"
    folder: "content/lookbook"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Coleção", name: "collection", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Descrição", name: "description", widget: "text" } 